# #####################################################################
# Automatically generated by qmake (2.01a) mer. f�vr. 24 10:34:20 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += gerertypestables.h \
    mainwindow.h \
    patientmodel.h \
    personnemodel.h \
    tableamanger.h \
    typetable.h \
    dialogsalleconceptor.h \
    typetableview.h \
    tableamangerview.h \
    gestionaffinites.h \
    sauvegarde.h \
    tableview.h \
    arriveewizard.h \
    arrivwizardpagepersonne.h \
    arrivwizardpagepatient.h \
    arrivwizardpagesurveillant.h \
    arrivwizardpageautre.h \
    arrivwizardpagerecapitulatif.h \
    surveillantmodel.h \
    preparerrepas.h \
    cuisiniermodel.h \
    cuisinierview.h \
    repasmodel.h \
    surveillantview.h \
    autrepersonnelmodel.h \
    autrepersonnelview.h \
    arbredespatientsparmetier.h
FORMS += gerertypestables.ui \
    mainwindow.ui \
    dialogsalleconceptor.ui \
    gestionaffinites.ui \
    sauvegarde.ui \
    tableview.ui \
    preparerrepas.ui
SOURCES += gerertypestables.cpp \
    main.cpp \
    mainwindow.cpp \
    patientmodel.cpp \
    personnemodel.cpp \
    tableamanger.cpp \
    typetable.cpp \
    qtc-gdbmacros/gdbmacros.cpp \
    dialogsalleconceptor.cpp \
    typetableview.cpp \
    tableamangerview.cpp \
    gestionaffinites.cpp \
    sauvegarde.cpp \
    tableview.cpp \
    arriveewizard.cpp \
    arrivwizardpagepersonne.cpp \
    arrivwizardpagepatient.cpp \
    arrivwizardpagesurveillant.cpp \
    arrivwizardpageautre.cpp \
    arrivwizardpagerecapitulatif.cpp \
    surveillantmodel.cpp \
    preparerrepas.cpp \
    cuisiniermodel.cpp \
    cuisinierview.cpp \
    repasmodel.cpp \
    surveillantview.cpp \
    autrepersonnelmodel.cpp \
    autrepersonnelview.cpp \
    arbredespatientsparmetier.cpp
QT += sql
RESOURCES += chrysalide.qrc
