# #####################################################################
# Automatically generated by qmake (2.01a) mer. f�vr. 24 10:34:20 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += gerertypestables.h \
    gestiontable.h \
    mainwindow.h \
    patientmodel.h \
    personnemodel.h \
    tableamanger.h \
    typetable.h \
    dialogsalleconceptor.h \
    typetableview.h \
    tableamangerview.h
FORMS += gerertypestables.ui \
    gestiontable.ui \
    mainwindow.ui \
    dialogsalleconceptor.ui
SOURCES += gerertypestables.cpp \
    gestiontable.cpp \
    main.cpp \
    mainwindow.cpp \
    patientmodel.cpp \
    personnemodel.cpp \
    tableamanger.cpp \
    typetable.cpp \
    qtc-gdbmacros/gdbmacros.cpp \
    dialogsalleconceptor.cpp \
    typetableview.cpp \
    tableamangerview.cpp
QT += sql
