# #####################################################################
# Automatically generated by qmake (2.01a) mer. f�vr. 24 10:34:20 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += gerertypestables.h \
    gestiontable.h \
    mainwindow.h \
    patientmodel.h \
    personnemodel.h \
    tableamanger.h \
    typetable.h \
    dialogsalleconceptor.h \
    typetableview.h \
    tableamangerview.h \
    arriveepersonne.h \
    gestionaffinites.h \
    sauvegarde.h \
    rentrertables.h \
    tableview.h \
    dialogrepas.h \
    arriveewizard.h \
    arrivwizardpagepersonne.h \
    arrivwizardpagepatient.h \
    arrivwizardpagesurveillant.h \
    arrivwizardpageautre.h \
    arrivwizardpagerecapitulatif.h
FORMS += gerertypestables.ui \
    gestiontable.ui \
    mainwindow.ui \
    dialogsalleconceptor.ui \
    arriveepersonne.ui \
    gestionaffinites.ui \
    sauvegarde.ui \
    rentrertables.ui \
    tableview.ui \
    dialogrepas.ui
SOURCES += gerertypestables.cpp \
    gestiontable.cpp \
    main.cpp \
    mainwindow.cpp \
    patientmodel.cpp \
    personnemodel.cpp \
    tableamanger.cpp \
    typetable.cpp \
    qtc-gdbmacros/gdbmacros.cpp \
    dialogsalleconceptor.cpp \
    typetableview.cpp \
    tableamangerview.cpp \
    arriveepersonne.cpp \
    gestionaffinites.cpp \
    sauvegarde.cpp \
    rentrertables.cpp \
    tableview.cpp \
    dialogrepas.cpp \
    arriveewizard.cpp \
    arrivwizardpagepersonne.cpp \
    arrivwizardpagepatient.cpp \
    arrivwizardpagesurveillant.cpp \
    arrivwizardpageautre.cpp \
    arrivwizardpagerecapitulatif.cpp
QT += sql
RESOURCES += chrysalide.qrc
